# Generated by Django 5.0.6 on 2024-10-31 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservaHotel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_departamento", models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="reserva",
            name="precio_total",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_municipio", models.TextField(max_length=100)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservaHotel.departamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="hoteles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_hotel", models.TextField(max_length=100)),
                ("direccion", models.TextField(max_length=100)),
                ("telefono", models.TextField(max_length=100)),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservaHotel.municipio",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="departamento",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reservaHotel.pais"
            ),
        ),
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo_electronico", models.EmailField(max_length=200)),
                ("nombre", models.TextField(max_length=200)),
                ("apellido", models.TextField(max_length=200)),
                ("pais_nacimiento", models.TextField(max_length=200)),
                ("departamento_nacimiento", models.TextField(max_length=200)),
                ("municipio_nacimiento", models.TextField(max_length=200)),
                ("telefono", models.TextField(max_length=200)),
                ("contrasena", models.TextField(max_length=20)),
                ("confirma_contrasena", models.TextField(max_length=20)),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservaHotel.municipio",
                    ),
                ),
            ],
        ),
    ]
