# Generated by Django 5.0.6 on 2024-10-31 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.TextField(max_length=100)),
                ("apellidos", models.TextField(max_length=50)),
                ("direccion", models.TextField(max_length=100)),
                ("telefono", models.TextField(max_length=100)),
                ("email", models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_departamento", models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="hoteles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_hotel", models.TextField(max_length=100)),
                ("direccion", models.TextField(max_length=100)),
                ("telefono", models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("tipo", models.CharField(max_length=50)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "hoteles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mi_reservacion.hoteles",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_municipio", models.TextField(max_length=100)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mi_reservacion.departamento",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hoteles",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mi_reservacion.municipio",
            ),
        ),
        migrations.AddField(
            model_name="departamento",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mi_reservacion.pais"
            ),
        ),
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo_electronico", models.EmailField(max_length=200)),
                ("nombre", models.TextField(max_length=200)),
                ("apellido", models.TextField(max_length=200)),
                ("pais_nacimiento", models.TextField(max_length=200)),
                ("departamento_nacimiento", models.TextField(max_length=200)),
                ("municipio_nacimiento", models.TextField(max_length=200)),
                ("telefono", models.TextField(max_length=200)),
                ("contrasena", models.TextField(max_length=20)),
                ("confirma_contrasena", models.TextField(max_length=20)),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mi_reservacion.municipio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_entrada", models.DateField()),
                ("fecha_salida", models.DateField()),
                ("precio_total", models.IntegerField(default=0)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mi_reservacion.cliente",
                    ),
                ),
                (
                    "habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mi_reservacion.habitacion",
                    ),
                ),
            ],
        ),
    ]
